### ISSUE TITLE
Unable to unstrip mscorlib

### ISSUE THREAD

**Issue by krulci** [BepInEx/Il2CppInterop#104]
I am having trouble unstripping `mscorlib.dll`.
I have tried the following two builds:
I compiled the same unity version of the game in `mono` and included `mscorlib.dll` from the `mono` build.
I compiled the same unity version of the game in `il2cpp` and included `mscorlib.dll` from the `il2cpp` build.
Both of them is giving me the following error:
```
System.ArgumentNullException: 'Value cannot be null. (Parameter 'type')'
```
I tried both build with the legacy `Il2cppAssemblyUnhollower`.
Both was able to be unstriped.
How may I fix this issue?

**Comment by krulci** [comment]
![image](https://github.com/BepInEx/Il2CppInterop/assets/52474054/791ca112-ba48-4511-ab26-be1d55bd344d)
In `Il2cppAssemblyUnhollower` it is finding this type in `mscorlib.dll`
![image](https://github.com/BepInEx/Il2CppInterop/assets/52474054/6039c925-c847-4063-9273-db4a95845f0f)
However, in `Il2CppInterop` it is finding this type in `System.Private.CoreLib.dll`

**Comment by ds5678** [comment]
I think this has been resolved sometime since you posted your issue because the core library references are constructed differently now.
