### ISSUE TITLE
Nested Types causing System.AccessViolationException

### ISSUE THREAD

**Issue by Dean2k** [BepInEx/Il2CppInterop#116]
![image](https://github.com/BepInEx/Il2CppInterop/assets/5357629/987d9e44-dc58-4a18-94b9-d99a811ae4b7)
![image](https://github.com/BepInEx/Il2CppInterop/assets/5357629/f90d8426-10d9-4151-981c-78896b8b7469)

**Comment by ds5678** [comment]
VRC uses anti-cheat. Are you able to reproduce this problem on a normal game?
