### ISSUE TITLE
Rewired: non-valid Unicode characters in generic parameter name

### ISSUE THREAD

**Issue by laymain** [BepInEx/Il2CppInterop#130]
Hi,

Il2CppInterop happens to generate non valid method/type names with some unicode characters.

In my case, it occurs with the Rewired library, it produces the following type name:
``Il2CppRewired_Core.dll Has an Invalid Type Name String "MethodInfoStoreGeneric_nqXVGKvgfzozBIAcnvWAyMFzaDld_Internal_Static_Int32_IList_1_☺_Predicate_1_☺_Int32_0`1"``
which contains two `SOH` (U+0001) characters.

See https://github.com/LavaGang/MelonLoader/issues/659

**Comment by laymain** [comment]
Here is the method prototype that causes the issue:
``internal static int nqXVGKvgfzozBIAcnvWAyMFzaDld<\u0001>(IList<\u0001> P_0, Predicate<\u0001> P_1, int P_2) where \u0001 : Element``

**Comment by ds5678** [comment]
@laymain Can you test #154?

**Comment by laymain** [comment]
Hi @ds5678, thanks for your update.

However the issue isn't fixed, invalid characters are still present:

![image](https://github.com/user-attachments/assets/d9c6fa33-f93f-4f0f-bd2a-8724903e347f)

Here is the dll, it may help: https://filetransfer.io/data-package/ItWPVhJV#link
