### ISSUE TITLE
Cannot implement Interfaces

### ISSUE THREAD

**Issue by bananplayss** [BepInEx/Il2CppInterop#191]
Hello! I'm modding a third party Unity game, and I would like to make an inventory UI system. For that I use the IPointer interfaces, but it didn't seem to work. 
I'm getting nullreference exceptions when I try to hover over a UI object. Code attached.
Thanks!
![image](https://github.com/user-attachments/assets/a10596e9-9806-4e84-af7c-650a3e97637a)
![image](https://github.com/user-attachments/assets/5c35e514-c4cb-4dbd-bdbb-efeceae43759)
![image](https://github.com/user-attachments/assets/fe08c2c1-a7e6-4744-b697-689c2a21aa3e)

**Comment by ds5678** [comment]
Are you sure invStorage isn't null?

**Comment by bananplayss** [comment]
> Are you sure invStorage isn't null?

No its definitely not, I debugged it. I think the interface doesn't seem to know their methods or doesn't see them as a method I believe. But it could be else

**Comment by ds5678** [comment]
Does pointer event data inherit from Il2CppSystem.ValueType?

**Comment by bananplayss** [comment]
> Does pointer event data inherit from Il2CppSystem.ValueType?

I'm not at home to check but how can I verify, and if not how can I make it inherit il2cpp's valuetype? The interface itself does as far as I remember

**Comment by ds5678** [comment]
ILSpy

**Comment by bananplayss** [comment]
I'm home, wouldn't it generate errors if it wasn't an il2cpp valuetype?

**Comment by ds5678** [comment]
@bananplayss Are you still experiencing the issue?
