### ISSUE TITLE
Add support for Il2Cpp metadata version 29

### ISSUE THREAD

**Issue by ghorsington** [BepInEx/Il2CppInterop#41]
This currently affects Unity versions 2021 and newer. At the moment, the following issues are present:

* Class::init signature lookup doesn't work
* Delegate injection doesn't seem to work either

**Comment by Michael-Ziluck** [comment]
Heya! Do you have any idea when you might get to this issue? Not necessarily anything definitive, even a vague "it's on my radar, maybe within the next X weeks/months" would even be great. I get that you guys do this project in your free time, so definitely not trying to be a nuisance about this and very much appreciate any and all help.

**Comment by ghorsington** [comment]
#55 for initial v29 support was merged in and released. Not yet closing this issue though since it requires testing

In terms of BepInEx, [Bleeding Edge builds](https://builds.bepinex.dev/projects/bepinex_be) starting version 6.0.0-be.663
