### ISSUE TITLE
Creating a new Il2CppStructArray has a chance to cause a InvalidOperationException

### ISSUE THREAD

**Issue by r-Lxd** [BepInEx/Il2CppInterop#82]
Depending on what game you're trying to mod (I was doing this on Sons of the Forest), this [Line](https://github.com/BepInEx/Il2CppInterop/blob/b976fade133aae96af0def04adaee754f1b182cb/Il2CppInterop.Runtime/Il2CppClassPointerStore.cs#L68) will throw a `InvalidOperationException (Sequence contains more than one matching element)` error

This causes old libraries such as UniverseLib to break.

I fixed this by manually changing `Select` to `FirstOrDefault` in DnSpy

**Comment by Kasuromi** [comment]
This isn't an issue with Il2CppInterop, we assume that there will be one instance of `Il2Cppmscorlib.dll` present in the AppDomain. Swapping `Single` for `First` only moves the issue to another place and you might run into a problem where something references the 1st loaded Il2Cppmscorlib but another references the 2nd one.

In the case of UniverseLib, it's a [known issue with UniverseLib](https://github.com/sinai-dev/UniverseLib/pull/9) that it loads multiple new AssemblyLoadContexts.

If your plugin is using `Assembly.LoadFile`, you should switch to `Assembly.LoadFrom` to ensure you are loading the assembly in the default context which would prevent multiple instances being present.
